### ISSUE TITLE
Комментарии к проекту.

### ISSUE THREAD

**Issue by mamontov-cpp** [permyakov-i/cppjudge#1]
Нужно, чтобы в проекте было хоть какое-то подобие комментариев к функциям и методам, пока вообще ничего непонятно и не видно.

**Comment by mamontov-cpp** [comment]
И формы переименуйте с дефолтных Form1 во что-то адекватное.

**Comment by permyakov-i** [comment]
Сделано. (коммит https://github.com/permyakov-i/cppjudge/commit/88ab9264b1c3ffbc84ea66c1b0f177eb60cb94f2)

**Comment by mamontov-cpp** [comment]
Форма по-прежнему в мастере не переименована.

**Comment by permyakov-i** [comment]
Переименована, просто я не убрал ее из индекса. (теперь убрал)

**Comment by mamontov-cpp** [comment]
Закрываю.
