### ISSUE TITLE
Вынести настройки в опции

### ISSUE THREAD

**Issue by mamontov-cpp** [permyakov-i/cppjudge#2]
Нужно вынести в опции:

Путь к компилятору, 
Оценки за задания,
Ограничения по памяти и времени.

**Comment by permyakov-i** [comment]
Каким образом должна выглядеть опция оценок? Выбирать сколько баллов стоит один тест?

**Comment by permyakov-i** [comment]
Сделано кроме оценок (коммиты https://github.com/permyakov-i/cppjudge/commit/5ece404eab90676342f5065b56780bf8dcc95821 https://github.com/permyakov-i/cppjudge/commit/d4e5c05fe6625c9ff52282bb45e795eda8ef8a12 https://github.com/permyakov-i/cppjudge/commit/6830d1440d0019b49a5f6cc600f863aaa500e4f4)

**Comment by mamontov-cpp** [comment]
Так, как это сделано в оригинальном скрипте.

**Comment by permyakov-i** [comment]
Добавил d5a8e5843426f5a5d3528273868039b240dfda3b 275ede5596dae8ab9aa4cccc6eba1ab8ac71c899

**Comment by mamontov-cpp** [comment]
Видел, но сделайте нормальный формат конфига. Ну есть же ini. json, xml. 
Почему у вас конфиг в plain text?

**Comment by permyakov-i** [comment]
Хорошо, переделаю в ini.

**Comment by mamontov-cpp** [comment]
Пока ок.
