### ISSUE TITLE
Программа не ограничивает время исполнения внутреннего процесса

### ISSUE THREAD

**Issue by mamontov-cpp** [permyakov-i/cppjudge#3]
https://msdn.microsoft.com/ru-ru/library/fb4aw7b8(v=vs.110).aspx

Нужно, чтобы программа убивала процесс, если он не завершается в заданный срок.

**Comment by permyakov-i** [comment]
Добавил https://github.com/permyakov-i/cppjudge/commit/8cdaf27c213d823ace1420167892b4a6aeeaaf7c.

**Comment by mamontov-cpp** [comment]
А вы проверили это на долго выполняющейся программе? Оно работает?

**Comment by permyakov-i** [comment]
Работало, но нестабильно, поменял способ, которым определялся таймаут.

**Comment by mamontov-cpp** [comment]
Да,  это более корректно
