### ISSUE TITLE
Сделать проверку на ошибку сегментации исполняемого процесса

### ISSUE THREAD

**Issue by mamontov-cpp** [permyakov-i/cppjudge#9]
По-прежнему не сделано в вашей программе.

**Comment by permyakov-i** [comment]
Сделал проверку при запуске теста, но насколько я выяснил G++ не отслеживает ошибки сегментации при компиляции, что приводит к падению программы во время тестирования, а я при этом только вывожу что произошла ошибка сегментации, так и нужно? Или мне нужно каким то образом предотвратить падение?

**Comment by mamontov-cpp** [comment]
Проверка кода возврата достаточна. Но вынесите его в константу. И наконец подумайте об архитектуре ,у вас предзащита на носу, а у вас архитектура дальше форм пока не идёт.

**Comment by permyakov-i** [comment]
Вынес в константу, насчет архитектуры помню, просто решил что сначала следует функционал добить.

**Comment by mamontov-cpp** [comment]
Ок, тогда архитектуру утаскиваю в подчистить код. Это закрываем.
